### PR TITLE
bsdunzip: make it possible to pass filenames starting with dash

### PR DESCRIPTION
**Pull request by Artoria2e5**
This is the consolidated version of some very messy comments I left on your PR. Just sleep-deprived chattiness.

### CODE REVIEW

**Comment by Artoria2e5** [comment]
The ifdef glibc bit is required here. Consider:

```
unzip -o a.zip -- -x.zip
```

This would work in BSD. However, in glibc, it gets rearranged to:
```
unzip -o -- a.zip -x.zip
```

And on a second pass we still blow up.

Yes, you could survive if you did `unzip -o -- a.zip -- -x.zip`, but come ON.

**Comment by AdrianVovk** [comment]
You clearly have a much better understanding of what's going on here w/ `getopt` than I do so I'll take your word on it. Thank you!

However, your last comment confuses me. It seems to imply that the change to the man page is no longer required. Let me know if this is ready for a merge

**Comment by Artoria2e5** [comment]
> However, your last comment confuses me. It seems to imply that the change to the man page is no longer required. Let me know if this is ready for a merge

It's ready. Now how do I explain this...

**Comment by Artoria2e5** [comment]
Okay. The manual page is for when both the archive and the file starts with a dash. In this situation you would need to `--` twice in both glibc and POSIX/BSD. I only used that one example because, well uh, I assume readers have a baseline expectation of `--` possibly being needed.

The second comment deals with glibc in particular and explains what happens when you put in something that works with BSD.

**Pull request merged**
